config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "contact", to: "static_pages#contact"
  post "make_contact", to: "static_pages#make_contact"

  get "about", to: "static_pages#about"
  get "delivery_info", to: "static_pages#delivery_info"

  resources :portfolio
    get 'portfolio/category/:category',  to: 'portfolio#index',  as: :portfolio_item_category
  resources :shop
    get 'shop/category/:category',       to: 'shop#index',       as: :shop_item_category

  devise_for :users, path: 'admin', class_name: "Admin::User", skip: [:registrations]
    as :user do
      get 'admin/users/edit', to: 'devise/registrations#edit', as: 'edit_registration'
      put 'admin/users/:id', to: 'devise/registrations#update', as: 'registration'
    end

  get "admin", to: "application#admin"
  namespace :admin do
    get  "content/home",          controller: :static_pages, action: :edit_home
    post "content/home",          controller: :static_pages, action: :update_home
    get  "content/about",         controller: :static_pages, action: :edit_about
    post "content/about",         controller: :static_pages, action: :update_about
    get  "content/delivery_info", controller: :static_pages, action: :edit_delivery_info
    post "content/delivery_info", controller: :static_pages, action: :update_delivery_info
    get  "content/contact",       controller: :static_pages, action: :edit_contact
    post "content/contact",       controller: :static_pages, action: :update_contact

    resources :portfolio
    get 'portfolio/:id/move_to_shop', to: 'portfolio#move_to_shop', as: 'move_portfolio_to_shop'

    resources :shop
    get 'shop/:id/move_to_portfolio', to: 'shop#move_to_portfolio', as: 'move_shop_to_portfolio'
  end

  root to: 'static_pages#home'
end

app/controllers/admin/portfolio_controller.rb
class Admin::PortfolioController < ApplicationController
  before_action :authenticate_user!

  def index
    @items = PortfolioItem.order("id")
  end

  def new
    @item = PortfolioItem.new
  end

  def create
    @item = PortfolioItem.create(portfolio_item_params)

    if @item.save
      flash["info"] = I18n.t('admin.create_successful', :page => "portfolio item")
      @items = PortfolioItem.all
      redirect_to admin_portfolio_index_path
    else
      flash["error"] = I18n.t('admin.create_failed', :page => "portfolio item")
      redirect_to new_admin_portfolio_path
    end
  end

  def edit
    @item = PortfolioItem.find_by_id(params[:id])
  end

  def update
    i = PortfolioItem.find_by_id(params[:id])
    if i.update_attributes!(portfolio_item_params)
      flash["info"] = I18n.t('admin.update_successful', :page => "portfolio item")
      @items = PortfolioItem.all
      redirect_to admin_portfolio_index_path
    else
      flash["error"] = I18n.t('admin.update_failed', :page => "portfolio item")
      @item = params[:portfolio_item]
      redirect_to edit_admin_portfolio_path(i.id)
    end
  end

  def destroy
    if PortfolioItem.delete(params[:id])
      flash["info"] = I18n.t('admin.delete_successful', :page => "portfolio item")
    else
      flash["error"] = I18n.t('admin.delete_failed', :page => "portfolio item")
    end

    @items = PortfolioItem.all
    redirect_to admin_portfolio_index_path
  end

  def move_to_shop
    source = begin
      PortfolioItem.find_by_id(params[:id])
    rescue ActiveRecord::RecordNotFound
      nil
    end

    if source.present? && source.is_a?(PortfolioItem)
      case source.move
        when -1 then flash["error"] = "Unable to create shop item. Please create and delete manually."
        when  0 then flash["error"] = "Item copied, but unable to delete portfolio item. Please delete manually."
        when  1 then flash["info"]  = "Item moved successfully."
        else flash["error"] = "Sorry, but something went wrong."
      end
    else
      flash["error"] = "Unable to find that portfolio item."
    end
    redirect_to admin_portfolio_index_path
  end

  private

  # Using a private method to encapsulate the permissible parameters
  # is just a good pattern since you'll be able to reuse the same
  # permit list between create and update. Also, you can specialize
  # this method with per-user checking of permissible attributes.
  def portfolio_item_params
    params.require(:portfolio_item).permit(
        :title, :description,
        :image_filename_1, :image_filename_2, :image_filename_3,
        :thumbnail_filename, :category_list, :enabled
    )
  end
end

app/controllers/portfolio_controller.rb
class PortfolioController < ApplicationController
  def index
    if params[:category]
      @items  = []
      @titles = []
      PortfolioItem.tagged_with(params[:category]).where(enabled: true).order("id").each do |i|
        @items  << i
        @titles << i.title
      end
    else
      taggings  = PortfolioItem.active_taggings
      @titles   = PortfolioItem.tag_names_from_taggings(taggings)
      @items    = PortfolioItem.first_items_from_tags_from_taggings(taggings)
    end
  end

  def show
    @item = PortfolioItem.find_by_id(params[:id])
    raise ActionController::RoutingError.new('Not Found') unless !@item.nil? && @item.enabled
  end
end

app/views/admin/portfolio/_form.html.erb
<%= form_for @item, url: {action: action} do |i| %>
  <%= i.label :title %>
  <%= i.text_field :title %>

  <%= i.label :description %>
  <%= i.text_area :description, class: "tinymce" %>

  <%= i.label :thumbnail_filename %>
  <%= i.text_field :thumbnail_filename %>

  <%= i.label :image_filename_1 %>
  <%= i.text_field :image_filename_1 %>

  <%= i.label :image_filename_2 %>
  <%= i.text_field :image_filename_2 %>

  <%= i.label :image_filename_3 %>
  <%= i.text_field :image_filename_3 %>

  <%= i.label :category_list %>
  <%= i.text_field :category_list, autocomplete: "off" %>

  <br /><br />

  <div>
    <%= i.check_box :enabled %>
    <%= i.label :enabled %>
  </div>

  <br />
  <%= submit_tag I18n.t('admin.portfolio.' + action), { class: "btn btn-success" } %>
<%- end -%>

app/views/admin/portfolio/edit.html.erb
<%- content_for :title do I18n.t('admin.page_editing') + I18n.t('page_titles.portfolio') end -%>

<%= render :partial => "form", locals: {action: "update"} %>

app/views/admin/portfolio/index.html.erb
<%- content_for :title do I18n.t('page_titles.portfolio') end -%>

<table id="portfolio-admin" class="table table-hover">
  <thead>
    <tr>
      <th><%= I18n.t('admin.portfolio.id') %></th>
      <th><%= I18n.t('admin.portfolio.title') %></th>
      <th><%= I18n.t('admin.portfolio.description') %></th>
      <th><%= I18n.t('admin.portfolio.images_count') %></th>
      <th><%= I18n.t('admin.page_actions') %></th>
    </tr>
  </thead>
  <tbody>
  <%- @items.each do |i| -%>
    <tr class="<%= "disabled" unless i.enabled %>">
      <td><%= image_tag i.thumbnail_filename.to_s, { alt: i.id.to_s, class: "span2" } %></td>
      <td><%= truncate(i.title, length: 50) %></td>
      <td><%= truncate(strip_tags(i.description), length: 50) %></td>
      <td><%= i.images_count %></td>
      <td>
        <%= link_to I18n.t('admin.portfolio.edit'), edit_admin_portfolio_path(i.id), { class: "btn btn-primary", type: "button" } %>
        <%= link_to I18n.t('admin.portfolio.destroy'), admin_portfolio_path(i.id), { class: "btn btn-primary", type: "button", method: :delete } %><br />
        <%= link_to I18n.t('admin.portfolio.move'), admin_move_portfolio_to_shop_path(i.id), { class: "btn btn-primary", type: "button" } %>
      </td>
    </tr>
  <%- end -%>
  </tbody>
</table>

<%= link_to I18n.t('admin.portfolio.create'), new_admin_portfolio_path, { class: "btn btn-primary", type: "button" } %>

app/views/admin/portfolio/new.html.erb
<%- content_for :title do I18n.t('admin.page_adding') + I18n.t('page_titles.portfolio') end -%>

<%= render :partial => "form", locals: {action: "create"} %>