config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "contact", to: "static_pages#contact"
  post "make_contact", to: "static_pages#make_contact"

  get "about", to: "static_pages#about"
  get "delivery_info", to: "static_pages#delivery_info"

  resources :portfolio
    get 'portfolio/category/:category',  to: 'portfolio#index',  as: :portfolio_item_category
  resources :shop
    get 'shop/category/:category',       to: 'shop#index',       as: :shop_item_category

  devise_for :users, path: 'admin', class_name: "Admin::User", skip: [:registrations]
    as :user do
      get 'admin/users/edit', to: 'devise/registrations#edit', as: 'edit_registration'
      put 'admin/users/:id', to: 'devise/registrations#update', as: 'registration'
    end

  get "admin", to: "application#admin"
  namespace :admin do
    get  "content/home",          controller: :static_pages, action: :edit_home
    post "content/home",          controller: :static_pages, action: :update_home
    get  "content/about",         controller: :static_pages, action: :edit_about
    post "content/about",         controller: :static_pages, action: :update_about
    get  "content/delivery_info", controller: :static_pages, action: :edit_delivery_info
    post "content/delivery_info", controller: :static_pages, action: :update_delivery_info
    get  "content/contact",       controller: :static_pages, action: :edit_contact
    post "content/contact",       controller: :static_pages, action: :update_contact

    resources :portfolio
    get 'portfolio/:id/move_to_shop', to: 'portfolio#move_to_shop', as: 'move_portfolio_to_shop'

    resources :shop
    get 'shop/:id/move_to_portfolio', to: 'shop#move_to_portfolio', as: 'move_shop_to_portfolio'
  end

  root to: 'static_pages#home'
end

app/controllers/admin/shop_controller.rb
class Admin::ShopController < ApplicationController
  before_action :authenticate_user!

  def index
    @items = ShopItem.order("id")
    @delivery_opts = StaticContent.load("shop", "delivery_opts")
  end

  def new
    @item = ShopItem.new
  end

  def create
    @item = ShopItem.create(shop_item_params)

    if @item.save
      flash["info"] = I18n.t('admin.create_successful', :page => "shop item")
      @items = ShopItem.all
      redirect_to admin_shop_index_path
    else
      flash["error"] = I18n.t('admin.create_failed', :page => "shop item")
      redirect_to new_admin_shop_path
    end
  end

  def edit
    @item = ShopItem.find_by_id(params["id"])
  end

  def update
    i = ShopItem.find_by_id(params[:id])
    if i.update_attributes!(shop_item_params)
      flash["info"] = I18n.t('admin.update_successful', :page => "shop item")
      @items = ShopItem.all
      redirect_to admin_shop_index_path
    else
      flash["error"] = I18n.t('admin.update_failed', :page => "shop item")
      @item = params[:shop_item]
      redirect_to edit_admin_shop_path(i.id)
    end
  end

  def destroy
    if ShopItem.delete(params[:id])
      flash["info"] = I18n.t('admin.delete_successful', :page => "shop item")
    else
      flash["error"] = I18n.t('admin.delete_failed', :page => "shop item")
    end

    @items = ShopItem.all
    redirect_to admin_shop_index_path
  end

  def move_to_portfolio
    source = begin
      ShopItem.find_by_id(params[:id])
    rescue ActiveRecord::RecordNotFound
      nil
    end

    if source.present? && source.is_a?(ShopItem)
      case source.move
        when -1 then flash["error"] = "Unable to create portfolio item. Please create and delete manually."
        when  0 then flash["error"] = "Item copied, but unable to delete shop item. Please delete manually."
        when  1 then flash["info"]  = "Item moved successfully."
        else flash["error"] = "Sorry, but something went wrong."
      end
    else
      flash["error"] = "Unable to find that shop item."
    end
    redirect_to admin_shop_index_path
  end

  private

  # Using a private method to encapsulate the permissible parameters
  # is just a good pattern since you'll be able to reuse the same
  # permit list between create and update. Also, you can specialize
  # this method with per-user checking of permissible attributes.
  def shop_item_params
    params.require(:shop_item).permit(
        :title, :description,
        :image_filename_1, :image_filename_2, :image_filename_3,
        :thumbnail_filename, :enabled,
        :quantity, :price, :category_list
    )
  end
end

app/controllers/shop_controller.rb
class ShopController < ApplicationController
  def index
    if params[:category]
      @items  = []
      @titles = []
      ShopItem.tagged_with(params[:category]).where(enabled: true).order("id").each do |i|
        @items  << i
        @titles << i.title
      end
    else
      taggings  = ShopItem.active_taggings
      @titles   = ShopItem.tag_names_from_taggings(taggings)
      @items    = ShopItem.first_items_from_tags_from_taggings(taggings)
    end
  end

  def show
    @item = ShopItem.find_by_id(params[:id])
    raise ActionController::RoutingError.new('Not Found') unless !@item.nil? && @item.enabled
  end
end

app/views/shop/_index_categories.html.erb
<%- content_for :title do I18n.t('page_titles.shop') end -%>

<div id="portfolio-gallery" class="span12">
<%- if @titles.present? -%>
  <p><%= I18n.t('shop.subhead_categories') %></p>
    <div class="row-fluid">
  <%- @titles.each_with_index do |tag_name, index| -%>
    <%- if (index % 3 == 0) && (index > 0) -%>
    </div>
    <div class="row-fluid">
    <%- end -%>
    <div class="portfolio-thumb span3">
      <%= link_to image_tag(@items[tag_name].thumbnail_filename.to_s), shop_item_category_path(tag_name) %>
      <p><%= @titles.at(index).to_s.capitalize -%></p>
    </div>
  <%- end -%>
<%- else -%>
  <p><%= I18n.t('shop.none_found') %></p>
<%- end -%>
</div>

app/views/shop/_index_category.html.erb
<%- content_for :title do I18n.t('page_titles.shop_category', :category => params[:category].capitalize) end -%>

<div id="portfolio-gallery" class="span12">
<%- if @items.present? -%>
  <p><%= I18n.t('shop.subhead_category') %></p>
    <div class="row-fluid">
  <%- @items.each_with_index do |item, index| -%>
    <%- if (index % 3 == 0) && (index > 0) -%>
    </div>
    <div class="row-fluid">
    <%- end -%>
    <div class="portfolio-thumb span3">
      <%= link_to image_tag(item.thumbnail_filename.to_s), shop_path(item.id) %>
      <p><%= item.title -%> <span class="item-price"><%= item.price %></span></p>
    </div>
  <%- end -%>
    </div>
<%- else -%>
  <p><%= I18n.t('shop.none_found_category') %></p>
<%- end -%>
</div>

app/views/shop/_shop_categories.html.erb
  <%- if @categories.present? -%>
    <ul>
    <%- @categories.each do |name| -%>
      <li><%= link_to name, shop_item_category_path(name) %></li>
    <%- end -%>
    </ul>
  <%- end -%>

app/views/shop/index.html.erb
<%= render partial: (params[:category].present? ? 'index_category' : 'index_categories') -%>

app/views/shop/show.html.erb
<%- content_for :title do @item.title end -%>

<div id="portfolio-item" class="span11">
  <div id="portfolio-images" class="span12">
    <%= image_tag @item.image_filename_1.to_s, { alt: "Image 1", class: "span3" } if @item.image_filename_1.present? %>
    <%= image_tag @item.image_filename_2.to_s, { alt: "Image 2", class: "span3" } if @item.image_filename_2.present? %>
    <%= image_tag @item.image_filename_3.to_s, { alt: "Image 3", class: "span3" } if @item.image_filename_3.present? %>
  </div>

  <div class="span12">
    <p><%= raw(@item.description) %></p>
    <p><span class="item-price"><%= @item.price %></span></p>
  </div>
</div>