config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "contact", to: "static_pages#contact"
  post "make_contact", to: "static_pages#make_contact"

  get "about", to: "static_pages#about"
  get "delivery_info", to: "static_pages#delivery_info"

  resources :portfolio
    get 'portfolio/category/:category',  to: 'portfolio#index',  as: :portfolio_item_category
  resources :shop
    get 'shop/category/:category',       to: 'shop#index',       as: :shop_item_category

  devise_for :users, path: 'admin', class_name: "Admin::User", skip: [:registrations]
    as :user do
      get 'admin/users/edit', to: 'devise/registrations#edit', as: 'edit_registration'
      put 'admin/users/:id', to: 'devise/registrations#update', as: 'registration'
    end

  get "admin", to: "application#admin"
  namespace :admin do
    get  "content/home",          controller: :static_pages, action: :edit_home
    post "content/home",          controller: :static_pages, action: :update_home
    get  "content/about",         controller: :static_pages, action: :edit_about
    post "content/about",         controller: :static_pages, action: :update_about
    get  "content/delivery_info", controller: :static_pages, action: :edit_delivery_info
    post "content/delivery_info", controller: :static_pages, action: :update_delivery_info
    get  "content/contact",       controller: :static_pages, action: :edit_contact
    post "content/contact",       controller: :static_pages, action: :update_contact

    resources :portfolio
    get 'portfolio/:id/move_to_shop', to: 'portfolio#move_to_shop', as: 'move_portfolio_to_shop'

    resources :shop
    get 'shop/:id/move_to_portfolio', to: 'shop#move_to_portfolio', as: 'move_shop_to_portfolio'
  end

  root to: 'static_pages#home'
end

app/views/layouts/_admin_links.html.erb
            <ul class="nav nav-list">
              <li class="<%= "active"  if active_action?("static_pages", "edit_home")    -%>"><%= link_to I18n.t('admin.page_editing') + I18n.t('page_titles.home'), admin_content_home_path -%></li>
              <li class="<%= "active"  if active_action?("static_pages", "edit_about")   -%>"><%= link_to I18n.t('admin.page_editing') + I18n.t('page_titles.about'), admin_content_about_path -%></li>
              <li class="<%= "active " if active_action?("shop")                         -%>"><%= link_to I18n.t('admin.page_editing') + I18n.t('page_titles.shop'), admin_shop_index_path -%></li>
              <li class="<%= "active"  if active_action?("static_pages", "delivery_info") -%>"><%= link_to I18n.t('admin.page_editing') + I18n.t('page_titles.delivery_info'), admin_content_delivery_info_path -%></li>
              <li class="<%= "active " if active_action?("portfolio")                    -%>"><%= link_to I18n.t('admin.page_editing') + I18n.t('page_titles.portfolio'), admin_portfolio_index_path -%></li>
              <!--li class="<%= "active " if active_action?("blog")                         -%>"><%= link_to I18n.t('admin.page_editing') + I18n.t('page_titles.blog'), "#" -%></li-->
              <li class="<%= "active"  if active_action?("static_pages", "edit_contact") -%>"><%= link_to I18n.t('admin.page_editing') + I18n.t('page_titles.contact'), admin_content_contact_path -%></li>
              <li class="active"><%= link_to('Change Password', edit_registration_path) %></li>
              <li class="active"><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
            </ul>

app/views/layouts/_google_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', '<%= ENV['GA_CODE'] %>', 'oddityavenue.com');
  ga('send', 'pageview');
</script>

app/views/layouts/_public_links.html.erb
            <ul class="nav nav-list">
              <li class="<%= "active"  if active_action?("static_pages", "home")    -%>"><%= link_to I18n.t('page_titles.home'), root_path -%></li>
              <li class="<%= "active"  if active_action?("static_pages", "about")   -%>"><%= link_to I18n.t('page_titles.about'), about_path -%></li>
              <li class="<%= "active " if active_action?("shop")                    -%>"><%= link_to I18n.t('page_titles.shop'), shop_index_path -%></li>
                <%= render partial: "shop_categories" if active_action?("shop") -%>
              <li class="<%= "active"  if active_action?("static_pages", "delivery_info") -%>"><%= link_to I18n.t('page_titles.delivery_info'), delivery_info_path -%></li>
              <li class="<%= "active " if active_action?("portfolio")               -%>"><%= link_to I18n.t('page_titles.portfolio'), portfolio_index_path -%></li>
                <%= render partial: "portfolio_categories" if active_action?("portfolio") -%>
              <!--li class="<%= "active " if active_action?("blog")                    -%>"><%= link_to  I18n.t('page_titles.blog'), root_path -%></li-->
              <li class="<%= "active"  if active_action?("static_pages", "contact") -%>"><%= link_to I18n.t('page_titles.contact'), contact_path -%></li>
            </ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title><%= I18n.t('app_name') -%></title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="<%= I18n.t('metadata.description') -%>">
    <meta name="author" content="<%= I18n.t('metadata.author') -%>">

    <%= stylesheet_link_tag    "bootstrap", :media => "all" %>
    <%= stylesheet_link_tag    "bootstrap-page-style", :media => "all" %>
    <%= stylesheet_link_tag    "application", :media => "all" %>

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="../assets/js/html5shiv.js"></script>
    <![endif]-->

    <!-- Fav and touch icons --> <!--
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
      <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
                    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
                                   <link rel="shortcut icon" href="../assets/ico/favicon.png"> -->
  </head>
  <body>
    <div class="container-fluid">
      <header class="row">
        <div id="logo" class="span5"></div>
        <div id="sublogo" class="span6 pull-right hidden-phone"></div>
      </header>
      <div class="row-fluid">
        <div id="sidebar" class="span2">
          <nav class="sidebar-nav">
<%= render :partial => (user_signed_in? ? "layouts/admin_links" : "layouts/public_links") -%>
          </nav>
        </div>
        <article class="content span10">
          <%- if content_for?(:title) -%><h2><%= yield :title %></h2><%- end -%>
          <%- if flash["error"]  -%><div class="error"><%= flash["error"]  %></div><%- end -%>
          <%- if flash["alert"]  -%><div class="error"><%= flash["alert"]  %></div><%- end -%>
          <%- if flash["notice"] -%><div class="info "><%= flash["notice"] %></div><%- end -%>
          <%- if flash["info"]   -%><div class="info "><%= flash["info"]   %></div><%- end -%>
          <%- flash.discard -%>
          <%= yield %>
        </article>
      </div>

      <hr>

      <footer>
        <p id="copyright">&copy; <%= I18n.t('metadata.copyright') -%> <%= Time.now.year -%></p>
        <%- if ENV['RAILS_ENV'] != 'production' -%><p id="env"><%= ENV['RACK_ENV'] %>:<%= ENV['RAILS_ENV'] %></p><%- end -%>
      </footer>

    </div>

    <%= render :partial => 'layouts/google_analytics' if ENV['GA_CODE'].present? %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "jquery" %>
    <%- if controller.controller_path.starts_with?("admin") -%>
      <%= javascript_include_tag "tinymce-jquery" -%>
      <%= tinymce_assets -%>
      <%= tinymce -%>
    <%- end -%>
  </body>
</html>